### ISSUE TITLE
ssdb实例coredump

### ISSUE THREAD

**Issue by koonin** [ideawu/ssdb#1000]
我们在导数据的时候，实例会经常出现coredump，机器配置是128G内存，SSD磁盘(6Gb/s)
coredump时候内存正常，没有out of memory；max open files正常；磁盘写200MB/s左右
但会经常出现以下2种情况的coredump：

(gdb) bt
#0  0x000000000044da33 in RedisLink::parse_req(Buffer*) ()
#1  0x000000000044fe39 in RedisLink::recv_req(Buffer*) ()
#2  0x00000000004503cf in Link::recv() ()
#3  0x0000000000447c48 in NetworkServer::serve() ()
#4  0x0000000000404578 in MyApplication::run() ()
#5  0x00000000004455cf in Application::main(int, char**) ()
#6  0x000000000040492f in main ()

(gdb) bt
#0  0x00007f862c15ba67 in memcpy () from /lib64/libc.so.6
#1  0x0000000000442f99 in Buffer::nice() ()
#2  0x000000000044cbfa in Link::read() ()
#3  0x00000000004458fd in NetworkServer::proc_client_event(Fdevent const*, std::vector<Link*, std::allocator<Link*> >*) ()
#4  0x0000000000447b4b in NetworkServer::serve() ()
#5  0x0000000000404578 in MyApplication::run() ()
#6  0x00000000004455cf in Application::main(int, char**) ()
#7  0x000000000040492f in main ()

**Comment by ideawu** [comment]
你好, 请问你使用的是哪一个版本?

**Comment by koonin** [comment]
1.9.2的版本
