### ISSUE TITLE
ssdb的zset对存入的元素长度是不是有限制？

### ISSUE THREAD

**Issue by BibiBabiBobi** [ideawu/ssdb#1013]
如果存入一个字符串，发现长度如果超过255，那么，ssdb就会报错：
Traceback (most recent call last):
  File "<pyshell#25>", line 1, in <module>
    mydb.zset('ljy_test', q, 0)
  File "C:\Python27\lib\site-packages\ssdb\client.py", line 1181, in zset
    return self.execute_command('zset', name, key, score)
  File "C:\Python27\lib\site-packages\ssdb\client.py", line 219, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "C:\Python27\lib\site-packages\ssdb\client.py", line 240, in parse_response
    raise DataError(RES_STATUS_MSG[status]+':'.join(response))
DataError: SSDB error.error
我使用的ssdb是0.0.3版本的

**Comment by BibiBabiBobi** [comment]
还是截图吧。。。
![image](https://cloud.githubusercontent.com/assets/10548274/20255231/db4459a6-aa75-11e6-8172-55d54865015f.png)

**Comment by yuikns** [comment]
ref: http://ssdb.io/docs/limit.html
