### ISSUE TITLE
用ssdb作为消息队列服务器时出现的问题

### ISSUE THREAD

**Issue by jinyachao** [ideawu/ssdb#1112]
有三台实例连接同一个ssdb消息队列服务器，从队列取数据消费时出现了异常，具体异常信息如下：
```
2017-07-20 16:12:14,887 [ssdb-receiver] ERROR com.asiainfo.mq.client.connection.ssdb.SSDBConnection$QueueingMessageReceiver.run(SSDBConnection.java:258)
 --- SSDBReceiver poll fail and retry it (queueName=WM_MC.TASK)
com.hyd.ssdb.SsdbClientException: should not be here
	at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:94)
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:102)
	at com.hyd.ssdb.AbstractClient.sendWriteRequest(AbstractClient.java:69)
	at com.hyd.ssdb.SsdbClient.qpopFront(SsdbClient.java:582)
	at com.asiainfo.mq.client.connection.ssdb.SSDBConnection$QueueingMessageReceiver.run(SSDBConnection.java:243)
	at java.lang.Thread.run(Thread.java:745)
```
这个问题 是因为ssdb连接有问题导致的吗，但是查日志的时候  也有其它的ssdb操作 都是正常的

**Comment by ideawu** [comment]
是客户端代码的使用问题，你可以从客户端代码查查。

**Comment by jinyachao** [comment]
好的，我先查查看，多谢
