### ISSUE TITLE
SSDB client GET 挂起

### ISSUE THREAD

**Issue by gwangyue** [ideawu/ssdb#1145]
GDB 堆栈信息如下：
#0  0x000000300d20ecdd in read () at ../sysdeps/unix/syscall-template.S:82
#1  0x00000000004a8275 in Link::read() ()
#2  0x00000000004abac6 in Link::response() ()
#3  0x00000000004a2cd7 in ssdb::ClientImpl::request(std::vector<std::string, std::allocator<std::string> > const&) ()
#4  0x00000000004a66b8 in ssdb::ClientImpl::request(std::string const&, std::string const&) ()
#5  0x00000000004a4418 in ssdb::ClientImpl::get(std::string const&, std::string*) ()
#6  0x000000000041fa12 in cmnews::ufs::SSDBClient::Get (this=this@entry=0x7fe57c000910, key=..., val=...) at src/engine/ssdb_client.cpp:79

背景：
1）开了10个线程，分别读同一个key。
2）不同的现场的链接，有可能复用（自己写了一个连接cluster）
3）偶尔会有一个线程挂起，挂起的堆栈信息如上

**Comment by gwangyue** [comment]
1）挂起原因是？
2）有什么解决方案

**Comment by ideawu** [comment]
问题应该出在你自己身上，也即连接复杂模块，极有可能是bug点。
