### ISSUE TITLE
ssdb死锁

### ISSUE THREAD

**Issue by zhanglistar** [ideawu/ssdb#1236]
ssdb hangs when zlist with args 500000, but not hang with 1000.
看了下代码，应该是SelectableQueue的push中调用的write pipe引发的问题导致整个程序死锁。
具体栈信息如下：
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7f6305452700 (LWP 19614)]
[New Thread 0x7f6305c53700 (LWP 19613)]
[New Thread 0x7f6306454700 (LWP 19612)]
[New Thread 0x7f6306c55700 (LWP 19611)]
[New Thread 0x7f6307456700 (LWP 19610)]
[New Thread 0x7f6307c57700 (LWP 19609)]
[New Thread 0x7f6308458700 (LWP 19608)]
[New Thread 0x7f6308c59700 (LWP 19607)]
[New Thread 0x7f630945a700 (LWP 19606)]
[New Thread 0x7f6309c5b700 (LWP 19605)]
[New Thread 0x7f630a45c700 (LWP 19604)]
[New Thread 0x7f630ac5d700 (LWP 19603)]
[New Thread 0x7f630b45e700 (LWP 19602)]
[New Thread 0x7f630bc5f700 (LWP 19601)]
[New Thread 0x7f630c460700 (LWP 19600)]
[New Thread 0x7f630cc61700 (LWP 19599)]
[New Thread 0x7f630d462700 (LWP 19598)]
[New Thread 0x7f630dc63700 (LWP 19597)]
[New Thread 0x7f630e464700 (LWP 19596)]
[New Thread 0x7f630ec65700 (LWP 19595)]
[New Thread 0x7f630f466700 (LWP 19594)]
[New Thread 0x7f630fc67700 (LWP 19593)]
[New Thread 0x7f6310468700 (LWP 19592)]
[New Thread 0x7f6310c69700 (LWP 19591)]
[New Thread 0x7f631146a700 (LWP 19590)]
[New Thread 0x7f6311c6b700 (LWP 19589)]
[New Thread 0x7f631246c700 (LWP 19588)]
[New Thread 0x7f6312c6d700 (LWP 19587)]
[New Thread 0x7f631346e700 (LWP 19586)]
[New Thread 0x7f6313c6f700 (LWP 19585)]
[New Thread 0x7f6314470700 (LWP 19584)]
[New Thread 0x7f6314c71700 (LWP 19583)]
[New Thread 0x7f6315472700 (LWP 19582)]
[New Thread 0x7f63187ff700 (LWP 19581)]
[New Thread 0x7f641efff700 (LWP 18889)]

warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffd216ef000
0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0

Thread 36 (Thread 0x7f641efff700 (LWP 18889)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000047f205 in leveldb::(anonymous namespace)::PosixEnv::BGThreadWrapper(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 35 (Thread 0x7f63187ff700 (LWP 19581)):
#0  0x00007f6420b00d7d in nanosleep () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f6420b32334 in usleep () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00000000004469c2 in ExpirationHandler::thread_func(void*) ()
#3  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 34 (Thread 0x7f6315472700 (LWP 19582)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 33 (Thread 0x7f6314c71700 (LWP 19583)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 32 (Thread 0x7f6314470700 (LWP 19584)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 31 (Thread 0x7f6313c6f700 (LWP 19585)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 30 (Thread 0x7f631346e700 (LWP 19586)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 29 (Thread 0x7f6312c6d700 (LWP 19587)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 28 (Thread 0x7f631246c700 (LWP 19588)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 27 (Thread 0x7f6311c6b700 (LWP 19589)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 26 (Thread 0x7f631146a700 (LWP 19590)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 25 (Thread 0x7f6310c69700 (LWP 19591)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 24 (Thread 0x7f6310468700 (LWP 19592)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 23 (Thread 0x7f630fc67700 (LWP 19593)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 22 (Thread 0x7f630f466700 (LWP 19594)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 21 (Thread 0x7f630ec65700 (LWP 19595)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 20 (Thread 0x7f630e464700 (LWP 19596)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 19 (Thread 0x7f630dc63700 (LWP 19597)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 18 (Thread 0x7f630d462700 (LWP 19598)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 17 (Thread 0x7f630cc61700 (LWP 19599)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 16 (Thread 0x7f630c460700 (LWP 19600)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 15 (Thread 0x7f630bc5f700 (LWP 19601)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 14 (Thread 0x7f630b45e700 (LWP 19602)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 13 (Thread 0x7f630ac5d700 (LWP 19603)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 12 (Thread 0x7f630a45c700 (LWP 19604)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 11 (Thread 0x7f6309c5b700 (LWP 19605)):
#0  0x00007f6420e11414 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000451feb in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 10 (Thread 0x7f630945a700 (LWP 19606)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 9 (Thread 0x7f6308c59700 (LWP 19607)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 8 (Thread 0x7f6308458700 (LWP 19608)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 7 (Thread 0x7f6307c57700 (LWP 19609)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7f6307456700 (LWP 19610)):
#0  0x00007f6420e1435d in write () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00000000004520a8 in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#2  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7f6306c55700 (LWP 19611)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7f6306454700 (LWP 19612)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7f6305c53700 (LWP 19613)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f6305452700 (LWP 19614)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000045203d in WorkerPool<ProcWorker, ProcJob*>::_run_worker(void*) ()
#4  0x00007f6420e0d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f6420b3a30d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f6421c527c0 (LWP 18888)):
#0  0x00007f6420e13f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6420e0f657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6420e0f480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00000000004516ee in SelectableQueue<ProcJob*>::pop(ProcJob**) ()
#4  0x000000000044ef94 in NetworkServer::serve() ()
#5  0x0000000000404968 in MyApplication::run() ()
#6  0x000000000044b66f in Application::main(int, char**) ()
#7  0x0000000000404d2f in main ()
```

**Comment by hww1996** [comment]
应该是触发写暂停了，这个跟ssdb没有关系，这个leveldb的锅
