### ISSUE TITLE
15台机器有3台就是连接不上SSDB

### ISSUE THREAD

**Issue by llongday** [ideawu/ssdb#1303]
机器也重装过了,设置了allow_ip  就是连接不上,是通过内网连接的
把其他12台机器的链接断掉也没用,不知道为什么
from pyssdb import Client
ssdb = Client(host='172.17.0.10')
ssdb.hsize('zhihu:user:article:author')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pyssdb.py", line 198, in wrapper
    data = func(self, cmd, *args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pyssdb.py", line 227, in execute_command
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pyssdb.py", line 223, in execute_command
    connection.send(cmd, *args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pyssdb.py", line 101, in send
    self._sock.sendall(buf)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by llongday** [comment]
IP filter存在BUG
使用list_allow_ip显示存在服务器但连接时在日志中显示
ip_filter deny link from *.*.*.*
 accept return NULL
最后使用统配方式解决,在ssdb.conf中设置allow为172.17

**Comment by JokerCatz** [comment]
docker default route is

172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255

so if you install docker as service ... don't use 172.17.x.x
