### ISSUE TITLE
关于连接超时和主从数据大小的一些疑问？

### ISSUE THREAD

**Issue by wefound** [ideawu/ssdb#886]
## 环境
 - vagrant centos6.5 64
 - mbp 
 - php5.6

### master
```
server:
	port: 20001
	ip: 0.0.0.0
	allow: 127.0.0.1
	allow: 192.168

```
### slave
```
server:
	ip: 0.0.0.0
	allow: 127.0.0.1
	allow: 192.168
	port: 20002

replication:
	binlog: yes
	sync_speed: -1
	slaveof:
		id: svc_1
		type: sync
		host: localhost
		port: 20001
```

## 测试日志

```
[root@vagrant-centos65 php]# php56 perf.php 
PHP Fatal error:  Uncaught exception 'SSDBTimeoutException' with message 'Connection timeout' in /opt/ssdb/api/php/SSDB.php:551
Stack trace:
#0 /opt/ssdb/api/php/SSDB.php(299): SSDB->recv()
#1 /opt/ssdb/api/php/SSDB.php(179): SSDB->recv_resp('set', Array)
#2 /opt/ssdb/api/php/perf.php(26): SSDB->__call('set', Array)
#3 /opt/ssdb/api/php/perf.php(26): SimpleSSDB->set('0000000631', '               ...')
#4 {main}
  thrown in /opt/ssdb/api/php/SSDB.php on line 551
[root@vagrant-centos65 php]# php56 perf.php 
PHP Fatal error:  Uncaught exception 'SSDBTimeoutException' with message 'Connection timeout' in /opt/ssdb/api/php/SSDB.php:551
Stack trace:
#0 /opt/ssdb/api/php/SSDB.php(299): SSDB->recv()
#1 /opt/ssdb/api/php/SSDB.php(179): SSDB->recv_resp('set', Array)
#2 /opt/ssdb/api/php/perf.php(26): SSDB->__call('set', Array)
#3 /opt/ssdb/api/php/perf.php(26): SimpleSSDB->set('0000000932', '               ...')
#4 {main}
  thrown in /opt/ssdb/api/php/SSDB.php on line 551

```

可以看到perf.php并没有执行多少操作就连接超时了。
看结果：

```
[root@vagrant-centos65 ssdb]# ll var/data/
total 32008
-rw-r--r-- 1 root root      267 Mar  5 03:54 000007.ldb
-rw-r--r-- 1 root root  3205764 Mar  5 04:01 000010.ldb
-rw-r--r-- 1 root root 26339897 Mar  5 04:01 000011.log
-rw-r--r-- 1 root root  3205511 Mar  5 04:01 000012.ldb
-rw-r--r-- 1 root root       16 Mar  5 03:54 CURRENT
-rw-r--r-- 1 root root        0 Mar  5 03:32 LOCK
-rw-r--r-- 1 root root      709 Mar  5 04:01 LOG
-rw-r--r-- 1 root root      172 Mar  5 03:33 LOG.old
-rw-r--r-- 1 root root      199 Mar  5 04:01 MANIFEST-000006
[root@vagrant-centos65 ssdb]# ll var_slave/data
total 157156
-rw-r--r-- 1 root root      290 Mar  5 03:57 000005.ldb
-rw-r--r-- 1 root root 67277797 Mar  5 04:01 000008.ldb
-rw-r--r-- 1 root root 26339897 Mar  5 04:01 000009.log
-rw-r--r-- 1 root root 67277842 Mar  5 04:01 000010.ldb
-rw-r--r-- 1 root root       16 Mar  5 03:57 CURRENT
-rw-r--r-- 1 root root        0 Mar  5 03:54 LOCK
-rw-r--r-- 1 root root      783 Mar  5 04:01 LOG
-rw-r--r-- 1 root root       57 Mar  5 03:54 LOG.old
-rw-r--r-- 1 root root      199 Mar  5 04:01 MANIFEST-000004
```

为什么 slave 的数据库会比 master 大这么多呢？
这个超时是什么引起的？

**Comment by ideawu** [comment]
数据库大小差异是正常的, 因为在不同的库中, 同样的数据集的排列和组织方式不同. 如果差异在下列范围是正常的:

1. 总数据集的大小在1G以内, 差异在500M以内
2. 总数据集大小大于1G, 差异在总数据集大小以内(即一个可能占用另一个的2倍硬盘空间).

一般情况下, 在小数据量时差异在100M以内, 大数据量(如500G)时, 差异在100G以内. 如果写越频繁, 差异可能越大.

**Comment by anissac** [comment]
@ideawu 有什么办法能够减小slave上面的db大小吗？另外 随着slave越来越大，是否会影响在slave上面的读性能。
